Tarefa #19
fegemo/cefet-games-brushmyteethplz pull request #41
Opened 2016-10-27 07:33 UTC by henriquegesler

Pausa foi implementada entre os jogos, não durante. Ela pode ser acessada com a tecla P.

2016-10-27 18:18 UTC, fegemo requested changes
Pessoal, a implementação precisa de melhorias e ainda introduz alguns problemas de desempenho e manutenibilidade. Por favor, avaliem se vocês estão dispostos a corrigi-los até hoje de noite, ou se preferem entregar como está (com prejuízo no valor em mangos na tarefa).

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +import static java.lang.Boolean.FALSE;
Não vejo razão para usar o [TRUE/FALSE objeto](http://stackoverflow.com/questions/20090306/what-is-the-difference-between-false-and-boolean-false) em vez de true/false primitivos. Tem justificativa? Isto introduz complexidade desnecessária ao código.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +    private boolean pause;
Prefira um nome de variável que não tenha ambiguidade, e.g., `isPaused`.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +    private final Texture grayMask, paused, unpaused;
Os nomes `paused` e `unpaused` não indicam que a variável armazena uma textura. Prefira algo como `pausedImage` ou `pausedTexture` etc.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        this.pause= FALSE;
`this.isPaused = false;`

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +            case WON:
Desnecessário incluir estas 4 linhas. Foque na sua atividade em questão.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                if(Gdx.input.isKeyJustPressed(Input.Keys.P)){
Interação via teclado não faz sentido para o nosso propósito.
Além disso, por quê foi feita a simplificação de que o jogo só pode ser pausado enquanto está havendo uma transição de MiniGames?

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                if(pause==FALSE){
Inverta a condição para melhorar a legibilidade - tipicamente, fica mais fácil colocarmos a "condição `true`" primeiro.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        this.paused = new Texture("images/paused.png");
Faça o pré-carregamento das imagens na classe `PlayingGamesScreen` e usando `super.assets.load` para que elas sejam carregadas apenas 1x na memória.

2016-10-27 18:18 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        this.paused = new Texture("images/paused.png");
Além disso, procure outras imagens - as selecionadas estão cheias de problemas, são mostradas grandes demais e chamam atenção demais.

2016-10-28 02:05 UTC, henriquegesler commented
O fork foi atualizado com as novas mudanças, porém o mouse continua sumindo no menu então não foi possível testar a função de click para o pause. Existe a implementação comentada dentro do if mas o P foi mantido. O countdown especifico falhou e não vai ser possível corrigir esse detalhe. Todos os seguintos foram atualizados.

2016-10-28 18:08 UTC, merged

2016-10-28 18:08 UTC, fegemo reviewed
Ainda há problemas, mas aceitei o pull request mesmo assim.

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                    if(isPaused){
É possível substituir estas 6 linhas (104-109) por apenas esta:

``` java
isPaused = !isPaused;
```

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                if(isPaused){
Não faz sentido manter uma cláusula `if` vazia .

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        if(isPaused){
Dá pra substituir as linhas 192-201 por apenas esta:

``` java
this.screen.batch.draw(isPaused ? pausedImage : unpausedImage, 0, 0, 125, 125);
```

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        this.pausedImage = screen.assets.get("images/pausedImage.png",
:+1:

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +        super.assets.load("images/pausedImage.png", Texture.class);
:+1:

2016-10-28 18:08 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                        Gdx.input.getY()>=0 && Gdx.input.getY()<=125*/){
Uso de números mágicos para a posição e dimensão do botão é uma prática muito ruim. Melhor seria ter isso definido em uma constante, ou um Rect instanciado no construtor.