Higor matheus 29 : + 1 mini game
fegemo/cefet-games-brushmyteethplz pull request #55
Opened 2016-11-03 08:53 UTC by higorcoimbra

2016-11-03 17:27 UTC, fegemo requested changes
Pessoal, preciso de algumas modificações no código do MiniGame (ele ficou muito legal!!). Vejam os comentários que fiz diretamente no código, por favor.

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +                        new CollectItensFactory.CarieSwordFactory(),
Creio que vocês sem querer arrastaram a classe `CarieSwordFactory` para dentro do arquivo `CollectItensFactory`.

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +        bg = new Texture(Gdx.files.internal("tooth-runner/fundo.png"));
Vocês não tem o direito de uso da imagem `fundo.png`. Ela é do site dreamstime (veja pela marcação na própria imagem). Aí vocês tem 3 opções: (a) fazer uma imagem vocês mesmos; (b) modificar a imagem que vocês pegaram e adaptá-la, mesclando com outras imagens; ou (c) verificar se o autor da imagem a licenciou para usos não comerciais, retirar as marcas d'água da imagem e usá-la.

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +        Gdx.input.setInputProcessor(
Aqui está acontecendo um problemão de desempenho (a máquina virtual do java estourou o espaço do _heap_ aqui):

- O método `onHandlePlayingInput()` é invocado dentro do `update()`, ou seja, a cada quadro
- Aqui dentro, seu código está instanciando um novo objeto que implementa a interface `InputProcessor` e instanciar novos objetos a cada quadro é péssimo para o desempenho. Tem casos que precisamos instanciar a cada quadro, mas neste não é necessário.
- Para corrigir, há pelo menos duas opções:
  1. (**minha sugestão**) Em vez de definir um processador de entradas, use apenas `if (Gdx.input.justTouched()) { /* ... */ }`
    - Esta é a melhor alternativa, visto que vocês escreverão bem menos código e não instanciarão nenhum objeto na memória desnecessariamente
  1.  Chamar `Gdx.input.setInputProcessor()` dentro do método `create` (que é chamado apenas 1x
    - Além dessa alteração, também será necessário chamar `Gdx.input.setInputProcessor(null)` ao final do MiniGame para que este processador de inputs seja "desligado" quando ele for encerrado

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +        delta += 4;
Ao colocar `delta += this.velocidade`, os pirulitos passam a estar colocados de acordo com o cenário em vez de parecer que estão em movimento. Há algum motivo para vocês não ter feito assim?

Além disso, há um problema quando o MiniGame é concluído (com vitória ou derrota): o jogador e os pirulitos param, mas o cenário continua mexendo. Isso acontece exatamente por causa desta linha, visto que ela não deveria fazer parte da função `onDrawGame()`, mas da `onUpdate()` (porque ela está atualizando lógica de jogo e não desenhando).

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +            this.screen.batch.draw(dente.atual, dente.sprite.getX()-10, dente.sprite.getY(),
Ao revisarem o código, peço que o "reformatem" usando o comando <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> do NetBeans

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +        for (int i = 0; i < 3; i++) {
Em vez de `i < 3`, criem uma constantezinha `MAX_ENEMIES` com valor 3, plz :smile:

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/factories/CollectItensFactory.java
> +
Parece que indevidamente vocês arrastaram o arquivo `CarieSwordFactory` para dentro do arquivo `CollectItensFactory`. Isso teve impacto aqui e no arquivo `PlayingGamesScreen`. Por favor, revejam.

2016-11-03 17:27 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +import br.cefetmg.games.minigames.factories.*;
Excelente ideia, Matheus!!!!

2016-11-03 18:30 UTC, fegemo commented
@higorcoimbra @matheus300

2016-11-03 18:41 UTC, matheus300 commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +                        new CollectItensFactory.CarieSwordFactory(),
Professor, quando fiz o fork do seu repositório atual, ele ja veio com esse tipo de instancia. Nao modifiquei nada do meu jogo antigo.

2016-11-03 18:43 UTC, matheus300 commented on core/src/br/cefetmg/games/minigames/ToothRunner.java
> +        delta += 4;
Professor, coloquei o pirulito a uma velocidade maior que a do cenário para que houvesse uma impressão de que o cenário está mais longe que o pirulito.

2016-11-03 18:51 UTC, matheus300 commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +import br.cefetmg.games.minigames.factories.*;
Ideia do IntelliJidea professor.

2016-11-04 00:35 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +import br.cefetmg.games.minigames.factories.*;
:+1:

2016-11-04 00:49 UTC, merged

2016-11-04 00:50 UTC, fegemo commented
MiniGame mesclado e tarefa entregue com sucesso!!