Alterações requisitadas
fegemo/cefet-games-brushmyteethplz pull request #59
Opened 2016-11-04 15:39 UTC by lcasviana

:D

2016-11-04 19:07 UTC, fegemo commented
@lcasviana, ainda não executei, mas olhando para o código parece que vocês optaram por não corrigir a gravidade do pulo, certo? Me parece também que o erro da música de fundo continuar tocando ainda permanece no MiniGame. Isso procede?

2016-11-05 00:44 UTC, lcasviana commented
Corrigido bug do som

2016-11-07 16:39 UTC, fegemo requested changes
Resolva os conflitos antes de enviar. O código enviado está completamente quebrado (não compila) por causa dos conflitos não resolvidos.

2016-11-07 16:39 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/SideWalking.java
> +<<<<<<< HEAD
Enviou conflitos sem resolução.

2016-11-07 16:41 UTC, closed without merging