Henrique thais 17
fegemo/cefet-games-brushmyteethplz pull request #72
Opened 2016-11-14 00:22 UTC by henriquegesler

Entrega da tarefa 17, do overwolrd.
Aconteceu um erro no buffer após a saída da tela do mundo que não conseguimos corrigir. Mexemos exaustivamente no código para tentar arrumar esse problema mas não conseguimos. As factories foram feitas de forma correto. Os atrasos foram devidos a esse problema, pois tentamos corrigir mas não conseguimos.

2016-11-14 11:11 UTC, fegemo commented
@henriquegesler, recebi o _pull request_, mas só poderei testá-lo pra ver se está tudo certo na quarta-feira.

2016-11-16 16:47 UTC, fegemo requested changes
@henriquegesler, fiz algumas observações no seu código e quero saber se você e a Thaís querem corrigi-las ou se vão entregar da forma como está, aceitando penalidades na nota (além do atraso da entrega).

Se optarem por corrigir os problemas, me avisem hoje (o quanto antes) e o prazo é até amanhã de noite.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +    private Object screen;
Criar uma instância de `Object` é raramente necessário e dificilmente uma boa ideia. Neste caso, esta variável nem está sendo usada, nem a `stage`.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +        if(Gdx.input.isButtonPressed(Input.Buttons.LEFT)){
`IsButtonPressed` (se não me engano) só vai funcionar para input via mouse. O correto seria `Gdx.input.justTouched()`.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +            if (Gdx.input.getX() > 0 && Gdx.input.getX() < 260
Há formas bem melhores disponibilizadas pela LibGDX para identificar se uma coordenada está dentro de um retângulo. Além disso, usar números mágicos (260, 420 etc.) é uma prática muito ruim de programação porque eles não têm nenhuma semântica.

Veja aqui um exemplo: http://stackoverflow.com/questions/25460029/is-this-the-right-way-to-detect-a-touch-on-a-rectangle-in-libgdx-does-not-seem (veja a resposta marcada como certa)

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +    public static final boolean DEV_MODE = true;
Remover todos os comandos de _debug_.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +            batch.draw(background, 0, 0,
Precisamos de algum tipo de indicação no mapa que comunique melhor o que são as fases e o que são os caminhos. Só de olhar o mapa, eu fiquei muito em dúvida (acho que não entendi que os quadrados amarelos eram caminhos. Talvez porque eles não têm um sentido (e.g., uma placa com uma setinha indicando o sentido), ou porque não possuem um formato de caminho (talvez um quadradinho por vez comunicaria melhor).

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +                if(DEV_MODE){
Retirar todos os comandos de _debugging_.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +    public static final boolean DEV_MODE = true;
Remover

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +             if (this.gt == GameType.LEARNING_ABOUT_CANDY){
É bem mais elegante, legível e melhor para a manutenibilidade do código usar um `switch` em vez de vários `if/elseif`.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +        batch.begin();
Faltou um botão "Voltar" para voltar à tela de Menu.

2016-11-16 16:47 UTC, fegemo commented on core/src/br/cefetmg/games/screens/Overworld.java
> +                //menuMusic.stop();
Remover código comentado.

2016-11-17 01:27 UTC, henriquegesler commented
Farei as correções aqui professor.

Desculpe a demora na resposta, só vi o email agora.
Vou olhar com a Thais apenas a questão da imagem porque foi ela que traduziu o meu desenho inicial pra 8-bits.

________________________________
De: Flávio Coutinho <notifications@github.com>
Enviado: quarta-feira, 16 de novembro de 2016 14:47
Para: fegemo/cefet-games-brushmyteethplz
Cc: henriquegesler; Mention
Assunto: Re: [fegemo/cefet-games-brushmyteethplz] Henrique thais 17 (#72)


@fegemo requested changes on this pull request.

@henriquegesler<https://github.com/henriquegesler>, fiz algumas observações no seu código e quero saber se você e a Thaís querem corrigi-las ou se vão entregar da forma como está, aceitando penalidades na nota (além do atraso da entrega).

Se optarem por corrigir os problemas, me avisem hoje (o quanto antes) e o prazo é até amanhã de noite.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +import com.badlogic.gdx.scenes.scene2d.Stage;
+import com.badlogic.gdx.utils.Timer;
+/**
+ *
+ * @author thais
+ */
+
+
+public class Overworld extends BaseScreen{
+
+    public static final boolean DEV_MODE = true;
+
+    private final Texture background;
+    //targetTexture;
+    private Stage stage;
+    private Object screen;


Criar uma instância de Object é raramente necessário e dificilmente uma boa ideia. Neste caso, esta variável nem está sendo usada, nem a stage.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +
+
+    }
+
+    @Override
+    public void appear() {
+
+    }
+
+    @Override
+    public void cleanUp() {
+    }
+
+    @Override
+    public void handleInput() {
+        if(Gdx.input.isButtonPressed(Input.Buttons.LEFT)){


IsButtonPressed (se não me engano) só vai funcionar para input via mouse. O correto seria Gdx.input.justTouched().

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +    }
+
+    @Override
+    public void appear() {
+
+    }
+
+    @Override
+    public void cleanUp() {
+    }
+
+    @Override
+    public void handleInput() {
+        if(Gdx.input.isButtonPressed(Input.Buttons.LEFT)){
+
+            if (Gdx.input.getX() > 0 && Gdx.input.getX() < 260


Há formas bem melhores disponibilizadas pela LibGDX para identificar se uma coordenada está dentro de um retângulo. Além disso, usar números mágicos (260, 420 etc.) é uma prática muito ruim de programação porque eles não têm nenhuma semântica.

Veja aqui um exemplo: http://stackoverflow.com/questions/25460029/is-this-the-right-way-to-detect-a-touch-on-a-rectangle-in-libgdx-does-not-seem (veja a resposta marcada como certa)

________________________________

In core/src/br/cefetmg/games/screens/PlayingGamesScreen.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> @@ -27,15 +27,18 @@
 public class PlayingGamesScreen extends BaseScreen
         implements GameStateObserver {

+    public static final boolean DEV_MODE = true;


Remover todos os comandos de debug.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +
+            }
+        }, 0.75f);// 750ms
+    }
+
+    @Override
+    public void update(float dt) {
+
+    }
+
+
+    @Override
+    public void draw() {
+        batch.begin();
+
+            batch.draw(background, 0, 0,


Precisamos de algum tipo de indicação no mapa que comunique melhor o que são as fases e o que são os caminhos. Só de olhar o mapa, eu fiquei muito em dúvida (acho que não entendi que os quadrados amarelos eram caminhos. Talvez porque eles não têm um sentido (e.g., uma placa com uma setinha indicando o sentido), ou porque não possuem um formato de caminho (talvez um quadradinho por vez comunicaria melhor).

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +                            + "; Y = " + Gdx.input.getY());
+                    }
+                    navigateToGamesScreen(GameType.LEARNING_ABOUT_HYGIENE);
+
+
+            } else if (Gdx.input.getX() > 680 && Gdx.input.getX() < viewport.getWorldWidth()
+                && Gdx.input.getY() > 280 && Gdx.input.getY() < 410){
+                    if(DEV_MODE){
+                        System.out.println("CARING: X = " + Gdx.input.getX()
+                            + "; Y = " + Gdx.input.getY());
+                    }
+                    navigateToGamesScreen(GameType.CARING_FOR_TEETH);
+
+
+            } else {
+                if(DEV_MODE){


Retirar todos os comandos de debugging.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +import com.badlogic.gdx.Game;
+import com.badlogic.gdx.Gdx;
+import com.badlogic.gdx.Input;
+import com.badlogic.gdx.graphics.Texture;
+import com.badlogic.gdx.graphics.g2d.Sprite;
+import com.badlogic.gdx.scenes.scene2d.Stage;
+import com.badlogic.gdx.utils.Timer;
+/**
+ *
+ * @author thais
+ */
+
+
+public class Overworld extends BaseScreen{
+
+    public static final boolean DEV_MODE = true;


Remover

________________________________

In core/src/br/cefetmg/games/screens/PlayingGamesScreen.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

>
-        if (this.option == GameOption.NORMAL) {
-            this.sequencer = new GameSequencer(5, new HashSet<MiniGameFactory>(
+        if (this.option == GameOption.NORMAL) {
+             if (this.gt == GameType.LEARNING_ABOUT_CANDY){


É bem mais elegante, legível e melhor para a manutenibilidade do código usar um switch em vez de vários if/elseif.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +                game.setScreen(new PlayingGamesScreen(game, Overworld.this,
+                        GameOption.NORMAL, gt));
+
+            }
+        }, 0.75f);// 750ms
+    }
+
+    @Override
+    public void update(float dt) {
+
+    }
+
+
+    @Override
+    public void draw() {
+        batch.begin();


Faltou um botão "Voltar" para voltar à tela de Menu.

________________________________

In core/src/br/cefetmg/games/screens/Overworld.java<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>:

> +                    System.out.println ("OUT: X = " + Gdx.input.getX()
+                        + "; Y = " + Gdx.input.getY());
+                }
+
+            }
+        }
+
+    }
+
+    private void navigateToGamesScreen(final GameType gt) {
+        transitionState = states.fadeOut;
+        Timer.schedule(new Timer.Task() {
+            @Override
+            public void run() {
+                transitionState = states.doNothing;
+                //menuMusic.stop();


Remover código comentado.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/fegemo/cefet-games-brushmyteethplz/pull/72#pullrequestreview-8850752>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AR0rxZvIwPjbTSKWA_lm0TPeJ86kD28Pks5q-zOKgaJpZM4Kw2v0>.

2016-11-17 21:55 UTC, henriquegesler commented
Não consigo resolver os conflitos... Estou tentando.

2016-11-17 22:06 UTC, henriquegesler commented
As correções foram feitas. Porém esta tendo algum problema na hora de fazer o pull request que nao estou conseguindo resolver... Mas as mudanças estão no repositorio.

2016-11-18 03:23 UTC, closed without merging