Botão pause acessível dentro dos minigames
fegemo/cefet-games-brushmyteethplz pull request #73
Opened 2016-11-15 13:42 UTC by dangon1

2016-11-16 17:03 UTC, fegemo requested changes
@dangon1 , fiz algumas observações no seu código e quero saber se você quer corrigi-las ou se vai entregar da forma como está, aceitando penalidades na nota (além do atraso da entrega).

Se optar por corrigir os problemas, me avise hoje (o quanto antes) e o prazo é até amanhã de noite.

2016-11-16 17:03 UTC, fegemo commented on core/src/br/cefetmg/games/screens/BaseScreen.java
> +    public BaseScreen getPrevious() {
Isto não é necessário. Vi que você colocou isto porque achou que era necessário na hora de trocar a tela, mas a tela `previous` é simplesmente a tela atual (`this`), ou seja: `super.game.setScreen(new MenuScreen(...), this)`.

2016-11-16 17:03 UTC, fegemo commented on core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> +        FINISHED_WON,
Esta vírgula está impedindo que o código compile.

2016-11-16 17:03 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/NinjaTooth.java
> +        if (!isPaused) {
Evite criar um pull request que altere outras coisas que não aquela para o qual ele foi criado.

Além disso, esta modificação é necessária pra que o pause funcione? Se for assim, será necessário modificar todos os MiniGames e isso seria péssimo (manutenibilidade 0).

2016-11-16 17:03 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                //System.out.println("remainingDuration:" + remainingDuration + " playingInitialTime:" + playingInitialTime);
Remover código comentado.

2016-11-16 17:03 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +    public boolean isPaused;
Por quê precisa ser `public`? Precisamos pensar bem antes de expor um campo porque isso pode ter impacto negativo no futuro.

2016-11-16 17:42 UTC, dangon1 commented
Professor, respondendo em ordem:

1. o *getPrevious()* realmente não tem necessidade de existir, eu tinha
feito para o botão voltar abrir a tela anterior, mas como você disse pode
ser o *this*.
2. vou retirar a vírgula.
3. Como dito no Trello, o *if (!isPaused) {* foi feito como tentativa de
evitar que jogos que sobrescrevem o método *OnUpdate*, continuassem
executando quando pausado. Mas mesmo com esse if não funcionou, então posso
somente retirá-lo, porém, jogos que sobrescrevem o *OnUpdate* ainda podem
manter algumas coisas executando com o tempo pausado. (Não consegui
solucionar isso). 4. Vou retirar o código comentado.
5. O *isPaused* está publico pois tive que acessá-lo do *NinjaTooth*, mas
este será retirado como dito no no. 3, então poderá ser private.


Consigo arrumar até amanhã à noite, exceto o problema explicado no.3.

Att.
Daniel Gonçalves

Em 16 de novembro de 2016 15:03, Flávio Coutinho <notifications@github.com>
escreveu:

> *@fegemo* requested changes on this pull request.
>
> @dangon1 <https://github.com/dangon1> , fiz algumas observações no seu
> código e quero saber se você quer corrigi-las ou se vai entregar da forma
> como está, aceitando penalidades na nota (além do atraso da entrega).
>
> Se optar por corrigir os problemas, me avise hoje (o quanto antes) e o
> prazo é até amanhã de noite.
> ------------------------------
>
> In core/src/br/cefetmg/games/screens/BaseScreen.java
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>
> :
>
> > @@ -201,6 +201,11 @@ public final void dispose() {
>          }
>          this.cleanUp();
>      }
> +
> +    public BaseScreen getPrevious() {
>
> Isto não é necessário. Vi que você colocou isto porque achou que era
> necessário na hora de trocar a tela, mas a tela previous é simplesmente a
> tela atual (this), ou seja: super.game.setScreen(new MenuScreen(...),
> this).
> ------------------------------
>
> In core/src/br/cefetmg/games/screens/PlayingGamesScreen.java
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>
> :
>
> > @@ -254,7 +254,7 @@ public void onTimeEnding(long endingTime) {
>      enum PlayScreenState {
>          PLAYING,
>          FINISHED_GAME_OVER,
> -        FINISHED_WON
> +        FINISHED_WON,
>
> Esta vírgula está impedindo que o código compile.
> ------------------------------
>
> In core/src/br/cefetmg/games/minigames/NinjaTooth.java
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>
> :
>
> > @@ -139,33 +139,35 @@ private void killTartarus(Bullet b,Tartarus enemy) {
>      @Override
>      public void onUpdate(float dt) {
>          // atualiza os inimigos (quadro de animação + colisão com dentes)
> -        if (superTooth.getHeadPosition().x > super.screen.viewport.getWorldWidth()
> -                || superTooth.getHeadPosition().x < 0
> -                || superTooth.getHeadPosition().y > super.screen.viewport.getWorldHeight()
> -                || superTooth.getHeadPosition().y < 0) {
> -
> -            superTooth.wasHurt();
> -            super.challengeFailed();
> -            toothBreakingSound.play();
> -        }
> +        if (!isPaused) {
>
> Evite criar um pull request que altere outras coisas que não aquela para o
> qual ele foi criado.
>
> Além disso, esta modificação é necessária pra que o pause funcione? Se for
> assim, será necessário modificar todos os MiniGames e isso seria péssimo
> (manutenibilidade 0).
> ------------------------------
>
> In core/src/br/cefetmg/games/minigames/MiniGame.java
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>
> :
>
> > @@ -214,6 +244,8 @@ private void transitionTo(MiniGameState newState) {
>          switch (newState) {
>              case PLAYING:
>                  playingInitialTime = TimeUtils.millis();
> +                remainingDuration += playingInitialTime;
> +                //System.out.println("remainingDuration:" + remainingDuration + " playingInitialTime:" + playingInitialTime);
>
> Remover código comentado.
> ------------------------------
>
> In core/src/br/cefetmg/games/minigames/MiniGame.java
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>
> :
>
> >      protected MiniGameState state;
>      protected Random rand;
>      protected Timer timer;
> -    private boolean isPaused;
> +    public boolean isPaused;
>
> Por quê precisa ser public? Precisamos pensar bem antes de expor um campo
> porque isso pode ter impacto negativo no futuro.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fegemo/cefet-games-brushmyteethplz/pull/73#pullrequestreview-8857963>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT7MwOAHAAVv0cPhNONTqVNAfzBcS1Poks5q-zdLgaJpZM4KyibJ>
> .
>

2016-11-18 18:59 UTC, fegemo reviewed
@dangon1, estou mesclando o seu pull request e alterando o que precisa ser feito pra que a pausa funcione corretamente. Fiz alguns comentários no pull request, mas vou fazer as alterações aqui mesmo (visto que estamos bem além do prazo).

2016-11-18 18:59 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/CarieEvasion.java
> +            if(!isPaused){
Investiguei o que está acontecendo aqui e descobri que a classe `AnimatedSprite` tem uma propriedade `autoUpdate = true` que faz com que sempre que o método `draw` é chamado (e ela é mesmo quando em pausa), ele invoca o método `update()` que, quando sobrescrito, está atualizando as posições das sprites de acordo com suas velocidades.

Na minha opinião, essa propriedade existir e ainda ter um valor padrão de `true` é um erro de projeto dessa classe `AnimatedSprite`. Contudo, para resolver sem criar um acoplamento com a propriedade `isPaused`, é melhor definir essa propriedade como `false` tão logo as instâncias de `AnimatedSprite` são criadas.

Vou fazer essa alteração aqui.

2016-11-18 18:59 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> -                    drawCountdown();
Qual o motivo para a remoção do _countdown_?

2016-11-18 18:59 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +                drawButtonPause();
O desenho do botão de pausa deve ser feito após o desenho da máscara para indicar que ele continua ativado. Vou fazer essa alteração aqui.

2016-11-18 18:59 UTC, fegemo commented on core/src/br/cefetmg/games/minigames/MiniGame.java
> +        this.remainingDuration = maxDuration;
Não entendi o uso desta variável. O nome dela diz: "duração restante", mas não vejo ela sendo decrementada... acho que ela pode estar provocando algum problema.

2016-11-20 15:11 UTC, merged

2016-11-20 15:14 UTC, fegemo commented
Pull request mesclado. Para completar/corrigir a funcionalidade de pausa, precisei destes _commits_: bdec21312ddc44a1cde4066e8968820c745179d7, 0822ccf, 8a31e02 e c069685.